#!/bin/bash
shopt -s expand_aliases

alias gf77='gfortran -std=legacy -w -ffixed-line-length-none'

SRC=../src/
FFLAGS='-fbacktrace'

rm -f *.o int2

gf77 $FFLAGS -c test_herm_p_rank1.f
gf77 $FFLAGS -c -o herm_p_rank1.o ${SRC}herm_p_rank1.f
gf77 $FFLAGS -c -o linalgwrap.o ${SRC}linalgwrap.f
gf77 $FFLAGS -c -o prini.o ${SRC}prini.f
gf77 $FFLAGS -c -o corrand.o ${SRC}corrand.f
gf77 $FFLAGS -o int2 test_herm_p_rank1.o herm_p_rank1.o linalgwrap.o \
  prini.o corrand.o \
-framework Accelerate

./int2
