#!/bin/bash
shopt -s expand_aliases

alias gf77='gfortran -std=legacy -w -ffixed-line-length-none'

SRC=../src/
FFLAGS='-fbacktrace -fopenmp'

rm -f *.o *.txt *.m int2

gf77 $FFLAGS -c test_zrootsq_adap.f
gf77 $FFLAGS -c -o ztest_functions.o ${SRC}ztest_functions.f
gf77 $FFLAGS -c -o zrootsq.o ${SRC}zrootsq.f
gf77 $FFLAGS -c -o csym_p_rank1.o ${SRC}csym_p_rank1.f
gf77 $FFLAGS -c -o prini.o ${SRC}prini.f
gf77 $FFLAGS -o int2 test_zrootsq_adap.o ztest_functions.o zrootsq.o \
  csym_p_rank1.o prini.o \
-framework Accelerate

./int2
